### ISSUE TITLE
How fix: AttributeError: 'DocumentMap' object has no attribute 'dragStartPos'?

### ISSUE THREAD

**Issue by daniilkorochansky** [TSN-ADMIN/wxPySTC_DocMap#2]
This:
line 165, in Motion     pos = (self.dragStartPos[0], top_y + self.hotspot[1]) AttributeError: 'DocumentMap' object has no attribute 'dragStartPos'

**Comment by TSN-ADMIN** [comment]
That:
Which version of source?
Which wxPython version?
Which Python version?
Try attaching your code here and help yourself whilst doing that.

**[Info on submitting a great issue](https://devsilv.github.io/2018/12/01/tips-to-submit-a-good-issue-on-github.html)**

The other:
Move line 134 above 133 and outdent

**Comment by TSN-ADMIN** [comment]
☆
